# Settings to be used by MP2RAGE-utils

# Input parameters
INV1path: "/path/to/file/MP2RAGE_INV1.nii"
INV2path: "/path/to/file/MP2RAGE_INV2.nii"
UNIpath: "/path/to/file/MP2RAGE_UNI.nii"
T1path: "/path/to/file/MP2RAGE_T1map.nii"

# MP2RAGE parameters
TIs: 800 2750 # left,right - save a grid gpl
FAs: 4 5 # top,bottom - save a grid gpl
